#!/usr/bin/env python3
"""Fail if a committed benchmark artifact no longer matches current code.

Why this exists
---------------
A README that quotes a committed JSON artifact is only as honest as the
freshness of that artifact. This repository previously shipped a headline
recovery figure taken from a benchmark artifact generated by an older version
of the strategist. Re-running the documented command produced a materially
different -- and worse -- number. Nobody had lied; the file had simply gone
stale while the code moved underneath it.

That is a reproducibility failure, and in a project whose entire thesis is
"count only what you can prove", it is the most damaging class of bug
available. So the freshness of every quoted number is now machine-enforced
rather than asserted:

    python -m scripts.check_artifacts

For each committed artifact this re-derives the run from its own recorded seed
and event count, then compares the metrics the README and docs actually quote.
Any drift exits non-zero, in CI as well as locally.

Pass ``--quick`` to check only the small artifacts, which is fast enough for a
pre-commit loop. CI runs the full check.

The artifacts are regenerated with:

    python -m scripts.run_benchmark --events <n> --seed <seed>
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from app.evaluation.counterfactual import sweep as sweep_counterfactual  # noqa: E402
from app.evaluation.generator import generate  # noqa: E402
from app.evaluation.harness import compare  # noqa: E402

RUNS_DIR = pathlib.Path(__file__).resolve().parents[2] / "evaluation" / "runs"

# The arms and fields quoted in README.md and docs/. Drift in any of these
# invalidates published claims, so each one is compared exactly.
CHECKED_FIELDS = (
    "recovered_revenue_rupees",
    "recovery_rate",
    "recovered_cases",
    "contacts_made",
    "policy_violations",
    "optimal_action_rate",
    "total_regret_rupees",
)

CHECKED_ARMS = (
    "learning",
    "recoveros",
    "fixed_baseline",
    "oracle",
    "ungoverned",
)

CHECKED_COUNTERFACTUAL_FIELDS = (
    "recovered_revenue_rupees",
    "recovery_rate",
    "recovered_cases",
    "contacts_made",
    "policy_violations",
    "optimal_action_rate",
    "total_regret_rupees",
    "revenue_delta_rupees",
    "contacts_delta",
    "verdict",
)


def check_benchmark(path: pathlib.Path) -> list[str]:
    """Re-run one benchmark artifact from its own recorded parameters and diff it."""
    committed = json.loads(path.read_text())
    dataset_meta = committed.get("dataset")
    if not dataset_meta:
        return [f"{path.name}: no dataset block; cannot verify provenance"]

    seed = dataset_meta["seed"]
    events = dataset_meta["events"]
    profile = dataset_meta.get("profile", "benchmark")

    fresh = compare(generate(n_events=events, seed=seed, profile=profile))

    problems: list[str] = []
    for arm in CHECKED_ARMS:
        old, new = committed.get(arm), fresh.get(arm)
        if old is None and new is None:
            continue
        if old is None or new is None:
            problems.append(f"{path.name}: arm '{arm}' appeared or disappeared")
            continue
        for field in CHECKED_FIELDS:
            if field not in old and field not in new:
                continue
            if old.get(field) != new.get(field):
                problems.append(
                    f"{path.name}: {arm}.{field}: "
                    f"committed={old.get(field)!r} current={new.get(field)!r}"
                )
    return problems


def check_counterfactual(path: pathlib.Path) -> list[str]:
    """Re-run one counterfactual sweep artifact from its parameters and diff it."""
    committed = json.loads(path.read_text())
    dataset_meta = committed.get("dataset")
    if not dataset_meta:
        return [f"{path.name}: no dataset block; cannot verify provenance"]

    seed = dataset_meta["seed"]
    events = dataset_meta["events"]
    profile = dataset_meta.get("profile", "benchmark")

    fresh = sweep_counterfactual(
        generate(n_events=events, seed=seed, profile=profile)
    ).to_dict()

    committed_variants = {v["variant"]: v for v in committed.get("variants", [])}
    fresh_variants = {v["variant"]: v for v in fresh.get("variants", [])}

    problems: list[str] = []
    for name, old in committed_variants.items():
        new = fresh_variants.get(name)
        if new is None:
            problems.append(f"{path.name}: variant '{name}' missing from fresh run")
            continue
        for field in CHECKED_COUNTERFACTUAL_FIELDS:
            if old.get(field) != new.get(field):
                problems.append(
                    f"{path.name}: variant '{name}'.{field}: "
                    f"committed={old.get(field)!r} current={new.get(field)!r}"
                )
    return problems


QUICK_MAX_EVENTS = 2000


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--quick",
        action="store_true",
        help=f"only verify artifacts of at most {QUICK_MAX_EVENTS} events",
    )
    args = parser.parse_args()

    benchmarks = sorted(RUNS_DIR.glob("run_benchmark_*.json"))
    counterfactuals = sorted(RUNS_DIR.glob("counterfactual_*.json"))

    if not benchmarks and not counterfactuals:
        print(f"no evaluation artifacts found in {RUNS_DIR}")
        return 1

    all_artifacts = [(p, check_benchmark) for p in benchmarks] + [
        (p, check_counterfactual) for p in counterfactuals
    ]

    if args.quick:
        kept = []
        for path, checker in all_artifacts:
            meta = json.loads(path.read_text()).get("dataset") or {}
            if meta.get("events", 0) <= QUICK_MAX_EVENTS:
                kept.append((path, checker))
            else:
                print(f"skip  {path.name} (--quick)")
        all_artifacts = kept

    print(f"verifying {len(all_artifacts)} committed evaluation artifact(s)\n")
    all_problems: list[str] = []
    for path, checker in all_artifacts:
        problems = checker(path)
        status = "ok   " if not problems else "DRIFT"
        print(f"{status} {path.name}")
        all_problems.extend(problems)

    if all_problems:
        print("\nARTIFACT DRIFT DETECTED\n")
        for problem in all_problems:
            print(f"  {problem}")
        print(
            "\nA committed artifact no longer matches current code, so any number "
            "quoted from it is stale.\nRegenerate the affected runs and update "
            "every doc that quotes them:\n"
            "    python -m scripts.run_benchmark --events <n> --seed <seed>\n"
            "    python -m scripts.run_counterfactual --events <n> --seed <seed>"
        )
        return 1

    print("\nall committed artifacts reproduce exactly from current code.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
