"""initial schema

Revision ID: 0001
Revises:

Created by hand rather than autogenerated so that the constraints enforcing
Invariant 1 are explicit and reviewable.
"""

from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "customers",
        sa.Column("id", sa.String(64), primary_key=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("contact", sa.String(32), nullable=False),
        sa.Column("lifetime_value_paise", sa.BigInteger(), server_default="0"),
        sa.Column("opted_out", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("contacts_this_window", sa.Integer(), server_default="0"),
        sa.Column("provenance", sa.String(32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.CheckConstraint("lifetime_value_paise >= 0", name="ck_customer_ltv_non_negative"),
    )
    op.create_index("ix_customers_opted_out", "customers", ["opted_out"])

    op.create_table(
        "risk_events",
        sa.Column("id", sa.String(64), primary_key=True),
        sa.Column("customer_id", sa.String(64), sa.ForeignKey("customers.id"), nullable=False),
        sa.Column("event_type", sa.String(48), nullable=False),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(3), nullable=False, server_default="INR"),
        sa.Column("reason", sa.String(48), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provenance", sa.String(32), nullable=False),
        sa.Column("external_ref", sa.String(128), nullable=True),
        sa.CheckConstraint("amount_paise > 0", name="ck_risk_event_amount_positive"),
    )
    op.create_index("ix_risk_events_customer", "risk_events", ["customer_id"])
    op.create_index("ix_risk_events_occurred_at", "risk_events", ["occurred_at"])

    op.create_table(
        "payment_evidence",
        sa.Column("id", sa.String(64), primary_key=True),
        sa.Column("external_payment_id", sa.String(128), nullable=False),
        sa.Column("external_event_id", sa.String(128), nullable=False),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("captured", sa.Boolean(), nullable=False),
        sa.Column("raw_event_type", sa.String(64), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("external_payment_id", name="uq_evidence_payment_id"),
        sa.CheckConstraint("captured = true", name="ck_evidence_must_be_captured"),
    )

    op.create_table(
        "recovery_cases",
        sa.Column("id", sa.String(64), primary_key=True),
        sa.Column("customer_id", sa.String(64), sa.ForeignKey("customers.id"), nullable=False),
        sa.Column("risk_event_id", sa.String(64), sa.ForeignKey("risk_events.id"), nullable=False),
        sa.Column("state", sa.String(32), nullable=False),
        sa.Column("revenue_at_risk_paise", sa.BigInteger(), nullable=False),
        sa.Column("recovered_amount_paise", sa.BigInteger(), nullable=True),
        sa.Column(
            "payment_evidence_id",
            sa.String(64),
            sa.ForeignKey("payment_evidence.id"),
            nullable=True,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("contacts_made", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("external_link_id", sa.String(128), nullable=True),
        sa.Column("recovery_probability", sa.Float(), nullable=True),
        sa.Column("provenance", sa.String(32), nullable=False),
        sa.Column("dataset_run_id", sa.String(128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint("risk_event_id", name="uq_case_per_risk_event"),
        sa.CheckConstraint("revenue_at_risk_paise > 0", name="ck_case_revenue_positive"),
        sa.CheckConstraint(
            "(recovered_amount_paise IS NULL AND payment_evidence_id IS NULL) "
            "OR (recovered_amount_paise IS NOT NULL AND payment_evidence_id IS NOT NULL)",
            name="ck_recovery_requires_evidence",
        ),
        sa.CheckConstraint(
            "state <> 'RECOVERED' OR payment_evidence_id IS NOT NULL",
            name="ck_recovered_state_requires_evidence",
        ),
    )
    op.create_index("ix_cases_state", "recovery_cases", ["state"])
    op.create_index("ix_cases_customer", "recovery_cases", ["customer_id"])
    op.create_index("ix_cases_link", "recovery_cases", ["external_link_id"])

    op.create_table(
        "policy_decisions",
        sa.Column("id", sa.String(64), primary_key=True),
        sa.Column("case_id", sa.String(64), sa.ForeignKey("recovery_cases.id"), nullable=False),
        sa.Column("allowed", sa.Boolean(), nullable=False),
        sa.Column("requires_human_approval", sa.Boolean(), nullable=False),
        sa.Column("policy_version_id", sa.String(64), nullable=False),
        sa.Column("policy_checksum", sa.String(64), nullable=False),
        sa.Column("rule_ids", sa.Text(), nullable=False),
        sa.Column("reasons", sa.Text(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_decisions_case", "policy_decisions", ["case_id"])

    op.create_table(
        "audit_records",
        sa.Column("id", sa.String(64), primary_key=True),
        sa.Column("case_id", sa.String(64), nullable=False),
        sa.Column("actor", sa.String(32), nullable=False),
        sa.Column("action", sa.String(64), nullable=False),
        sa.Column("from_state", sa.String(32), nullable=True),
        sa.Column("to_state", sa.String(32), nullable=True),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("policy_version_id", sa.String(64), nullable=True),
        sa.Column("decision_id", sa.String(64), nullable=True),
        sa.Column("external_event_id", sa.String(128), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_audit_case", "audit_records", ["case_id"])
    op.create_index("ix_audit_at", "audit_records", ["at"])
    op.create_index("ix_audit_action", "audit_records", ["action"])

    op.create_table(
        "webhook_events",
        sa.Column("id", sa.String(64), primary_key=True),
        sa.Column("external_event_id", sa.String(128), nullable=False),
        sa.Column("event_type", sa.String(64), nullable=False),
        sa.Column("signature_valid", sa.Boolean(), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("case_id", sa.String(64), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint("external_event_id", name="uq_webhook_event_id"),
    )


def downgrade() -> None:
    op.drop_table("webhook_events")
    op.drop_table("audit_records")
    op.drop_table("policy_decisions")
    op.drop_table("recovery_cases")
    op.drop_table("payment_evidence")
    op.drop_table("risk_events")
    op.drop_table("customers")
